fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.9.1"
    archive:
      repo: "puppet/archive"
      ref: "1.2.0"     
    docker:
      repo: "garethr/docker"
      ref: "4.1.1"       
    wget:
      repo: "maestrodev/wget"
      ref: "1.7.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "2.2.2"
  symlinks:
    grafana: "#{source_dir}"
